### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by 32bitx64bit** [illnyang/nvlax#19]
Im on Linux mint 20.3

heres the error

/home/gavin/nvlax/src/lax_encode.cc: In function ‘void patch_linux(LIEF::ELF::Binary*)’:
/home/gavin/nvlax/src/lax_encode.cc:45:78: error: request for member ‘value’ in ‘f_nvenc_ci’, which is of pointer type ‘LIEF::Symbol*’ (maybe you meant to use ‘->’ ?)
   45 | _func_bytes = bin->get_content_from_virtual_address(f_nvenc_ci.value(), 0x260);
      |                                                                ^~~~~

In file included from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Status.h:35,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Decoder.h:38,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Zydis.h:39,
                 from /home/gavin/nvlax/src/lax_encode.cc:17:
/home/gavin/nvlax/src/lax_encode.cc:51:29: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
   51 |         while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/zydis-src/dependencies/zycore/include/Zycore/Status.h:82:9: note: in definition of macro ‘ZYAN_SUCCESS’
   82 |     (!((status) & 0x80000000u))
      |         ^~~~~~
/home/gavin/nvlax/src/lax_encode.cc:53:37: error: request for member ‘value’ in ‘f_nvenc_ci’, which is of pointer type ‘LIEF::Symbol*’ (maybe you meant to use ‘->’ ?)
   53 |                 offset = f_nvenc_ci.value() +
      |                                     ^~~~~
/home/gavin/nvlax/src/lax_encode.cc:55:32: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
   55 |                          instr.operands[1].mem.disp.value;
      |                                ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:59:63: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
   59 |            if (instr.mnemonic == ZYDIS_MNEMONIC_MOV && instr.operands[0].mem.disp.value / 8 == 30) {
      |                                                              ^~~~~~~~

In file included from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Status.h:35,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Decoder.h:38,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Zydis.h:39,
                 from /home/gavin/nvlax/src/lax_encode.cc:17:
/home/gavin/nvlax/src/lax_encode.cc:82:29: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
   82 |         while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:82:16: note: in expansion of macro ‘ZYAN_SUCCESS’
   82 |         while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                ^~~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:84:23: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
   84 |                 instr.operands[0].reg.value == ZYDIS_REGISTER_EAX &&
      |                       ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:85:23: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
   85 |                 instr.operands[1].reg.value == ZYDIS_REGISTER_EAX &&
      |                       ^~~~~~~~
In file included from /home/gavin/nvlax/src/lax_encode.cc:19:
/home/gavin/nvlax/src/lax_encode.cc: In lambda function:
/home/gavin/nvlax/src/lax_encode.cc:145:39: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
  145 |         PPK_ASSERT_ERROR(ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:127:56: note: in definition of macro ‘PPK_ASSERT_LIKELY’
  127 |     #define PPK_ASSERT_LIKELY(arg) __builtin_expect(!!(arg), !0)
      |                                                        ^~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:605:50: note: in expansion of macro ‘PPK_ASSERT_3’
  605 |     #define PPK_ASSERT_2(level, expression, ...) PPK_ASSERT_3(level, expression, __VA_ARGS__)
      |                                                  ^~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:169:44: note: in expansion of macro ‘PPK_ASSERT_2’
  169 |   #define PPK_ASSERT_1(level, expression)  PPK_ASSERT_2(level, expression, PPK_ASSERT_NULLPTR)
      |                                            ^~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:87:39: note: in expansion of macro ‘PPK_ASSERT_1’
   87 |   #define PPK_ASSERT_JOIN__(lhs, rhs) lhs##rhs
      |                                       ^~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:73:46: note: in expansion of macro ‘PPK_ASSERT_’
   73 |   #define PPK_ASSERT_ERROR(...)              PPK_ASSERT_(ppk::assert::implementation::AssertLevel::Error, __VA_ARGS__)
      |                                              ^~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:145:9: note: in expansion of macro ‘PPK_ASSERT_ERROR’
  145 |         PPK_ASSERT_ERROR(ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder,
      |         ^~~~~~~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:145:26: note: in expansion of macro ‘ZYAN_SUCCESS’
  145 |         PPK_ASSERT_ERROR(ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder,
      |                          ^~~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:154:71: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  154 |                                                             &instr.operands[0],
      |                                                                    ^~~~~~~~

/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:127:56: note: in definition of macro ‘PPK_ASSERT_LIKELY’
  127 |     #define PPK_ASSERT_LIKELY(arg) __builtin_expect(!!(arg), !0)
      |                                                        ^~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:605:50: note: in expansion of macro ‘PPK_ASSERT_3’
  605 |     #define PPK_ASSERT_2(level, expression, ...) PPK_ASSERT_3(level, expression, __VA_ARGS__)
      |                                                  ^~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:169:44: note: in expansion of macro ‘PPK_ASSERT_2’
  169 |   #define PPK_ASSERT_1(level, expression)  PPK_ASSERT_2(level, expression, PPK_ASSERT_NULLPTR)
      |                                            ^~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:87:39: note: in expansion of macro ‘PPK_ASSERT_1’
   87 |   #define PPK_ASSERT_JOIN__(lhs, rhs) lhs##rhs
      |                                       ^~~
/home/gavin/nvlax/build/_deps/ppk_assert-src/src/ppk_assert.h:73:46: note: in expansion of macro ‘PPK_ASSERT_’
   73 |   #define PPK_ASSERT_ERROR(...)              PPK_ASSERT_(ppk::assert::implementation::AssertLevel::Error, __VA_ARGS__)
      |                                              ^~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:153:9: note: in expansion of macro ‘PPK_ASSERT_ERROR’
  153 |         PPK_ASSERT_ERROR(ZYAN_SUCCESS(ZydisCalcAbsoluteAddress(&instr,
      |         ^~~~~~~~~~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:153:26: note: in expansion of macro ‘ZYAN_SUCCESS’
  153 |         PPK_ASSERT_ERROR(ZYAN_SUCCESS(ZydisCalcAbsoluteAddress(&instr,
      |                          ^~~~~~~~~~~~
In file included from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Status.h:35,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Decoder.h:38,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Zydis.h:39,
                 from /home/gavin/nvlax/src/lax_encode.cc:17:
/home/gavin/nvlax/src/lax_encode.cc: In function ‘void patch_windows(LIEF::PE::Binary*)’:
/home/gavin/nvlax/src/lax_encode.cc:183:33: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
  183 |             while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/zydis-src/dependencies/zycore/include/Zycore/Status.h:82:9: note: in definition of macro ‘ZYAN_SUCCESS’
   82 |     (!((status) & 0x80000000u))
      |         ^~~~~~
/home/gavin/nvlax/src/lax_encode.cc:185:27: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  185 |                     instr.operands[1].type == ZYDIS_OPERAND_TYPE_MEMORY)
      |                           ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:189:34: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  189 |                            instr.operands[1].mem.disp.value;
      |                                  ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:194:27: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  194 |                     instr.operands[0].mem.disp.value / 8 == 30)
      |                           ^~~~~~~~
In file included from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Status.h:35,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Decoder.h:38,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Zydis.h:39,
                 from /home/gavin/nvlax/src/lax_encode.cc:17:
/home/gavin/nvlax/src/lax_encode.cc:206:33: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
  206 |             while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/zydis-src/dependencies/zycore/include/Zycore/Status.h:82:9: note: in definition of macro ‘ZYAN_SUCCESS’
   82 |     (!((status) & 0x80000000u))
      |         ^~~~~~
/home/gavin/nvlax/src/lax_encode.cc:209:27: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  209 |                     instr.operands[0].mem.base == ZYDIS_REGISTER_ESI &&
      |                           ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:210:27: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  210 |                     instr.operands[0].mem.disp.value / 4 == 31)
      |                           ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:213:68: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  213 |               offset = follow_thunk(bin->rva_to_offset(instr.operands[1].imm.value.u));
      |                                                              ^~~~~~~~

In file included from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Status.h:35,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Decoder.h:38,
                 from /home/gavin/nvlax/build/_deps/zydis-src/include/Zydis/Zydis.h:39,
                 from /home/gavin/nvlax/src/lax_encode.cc:17:
/home/gavin/nvlax/src/lax_encode.cc:234:29: error: ‘ZydisDecoderDecodeBuffer’ was not declared in this scope; did you mean ‘ZydisDecoderDecodeFull’?
  234 |         while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data, length, &instr))) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
/home/gavin/nvlax/build/_deps/zydis-src/dependencies/zycore/include/Zycore/Status.h:82:9: note: in definition of macro ‘ZYAN_SUCCESS’
   82 |     (!((status) & 0x80000000u))
      |         ^~~~~~
/home/gavin/nvlax/src/lax_encode.cc:236:23: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  236 |                 instr.operands[0].reg.value == ZYDIS_REGISTER_EAX &&
      |                       ^~~~~~~~
/home/gavin/nvlax/src/lax_encode.cc:237:23: error: ‘ZydisDecodedInstruction’ {aka ‘struct ZydisDecodedInstruction_’} has no member named ‘operands’
  237 |                 instr.operands[1].reg.value == ZYDIS_REGISTER_EAX &&
      |                       ^~~~~~~~
make[2]: *** [CMakeFiles/nvlax_encode.dir/build.make:95: CMakeFiles/nvlax_encode.dir/src/lax_encode.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: CMakeFiles/nvlax_encode.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by lars18th** [comment]
Hi @32bitx64bit ,

Please close this. You only need to apply the patch from @tytan652 : https://github.com/illnyang/nvlax/issues/11#issuecomment-1034079793

**Comment by Cat-Lady** [comment]
Why close, @lars18th? The version from this git still fails to build, and external patches need to be applied. The issue will be fixed, when the fix lands in the repository... Or, some fork takes over, cause, apparently, this one seems rather abandoned.

Besides, even with the patch, it *still* fails, with:
```In file included from /home/estel/utilities/nvlax/build/_deps/lief_src-src/src/ELF/NoteDetails/AndroidNote.cpp:21:
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:75:38: error: expected ')' before 'offset'
   75 |   explicit read_out_of_bound(uint64_t offset, uint64_t size);
      |                             ~        ^~~~~~~
      |                                      )
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:76:38: error: expected ')' before 'offset'
   76 |   explicit read_out_of_bound(uint64_t offset);
      |                             ~        ^~~~~~~
      |                                      )
make[5]: *** [CMakeFiles/LIB_LIEF.dir/build.make:1743: CMakeFiles/LIB_LIEF.dir/src/ELF/NoteDetails/AndroidNote.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /home/estel/utilities/nvlax/build/_deps/lief_src-src/src/ELF/NoteDetails/NoteAbi.cpp:21:
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:75:38: error: expected ')' before 'offset'
   75 |   explicit read_out_of_bound(uint64_t offset, uint64_t size);
      |                             ~        ^~~~~~~
      |                                      )
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:76:38: error: expected ')' before 'offset'
   76 |   explicit read_out_of_bound(uint64_t offset);
      |                             ~        ^~~~~~~
      |                                      )
make[5]: *** [CMakeFiles/LIB_LIEF.dir/build.make:1757: CMakeFiles/LIB_LIEF.dir/src/ELF/NoteDetails/NoteAbi.cpp.o] Error 1
In file included from /home/estel/utilities/nvlax/build/_deps/lief_src-src/src/exception.cpp:19:
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:75:38: error: expected ')' before 'offset'
   75 |   explicit read_out_of_bound(uint64_t offset, uint64_t size);
      |                             ~        ^~~~~~~
      |                                      )
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:76:38: error: expected ')' before 'offset'
   76 |   explicit read_out_of_bound(uint64_t offset);
      |                             ~        ^~~~~~~
      |                                      )
/home/estel/utilities/nvlax/build/_deps/lief_src-src/src/exception.cpp:50:1: error: no declaration matches 'LIEF::read_out_of_bound::read_out_of_bound(uint64_t, uint64_t)'
   50 | read_out_of_bound::read_out_of_bound(uint64_t offset, uint64_t size) : LIEF::exception("") {
      | ^~~~~~~~~~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note: candidates are: 'LIEF::read_out_of_bound::read_out_of_bound(LIEF::read_out_of_bound&&)'
   71 | class LIEF_API read_out_of_bound : public exception {
      |                ^~~~~~~~~~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const LIEF::read_out_of_bound&)'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note:                 'LIEF::read_out_of_bound::read_out_of_bound()'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const LIEF::exception&) [inherited from LIEF::exception]'
   73 |   using exception::exception;
      |                    ^~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(std::string) [inherited from LIEF::exception]'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const char*) [inherited from LIEF::exception]'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note: 'class LIEF::read_out_of_bound' defined here
   71 | class LIEF_API read_out_of_bound : public exception {
      |                ^~~~~~~~~~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/src/exception.cpp:58:1: error: no declaration matches 'LIEF::read_out_of_bound::read_out_of_bound(uint64_t)'
   58 | read_out_of_bound::read_out_of_bound(uint64_t offset) : LIEF::exception("") {
      | ^~~~~~~~~~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note: candidates are: 'LIEF::read_out_of_bound::read_out_of_bound(LIEF::read_out_of_bound&&)'
   71 | class LIEF_API read_out_of_bound : public exception {
      |                ^~~~~~~~~~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const LIEF::read_out_of_bound&)'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note:                 'LIEF::read_out_of_bound::read_out_of_bound()'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const LIEF::exception&) [inherited from LIEF::exception]'
   73 |   using exception::exception;
      |                    ^~~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(std::string) [inherited from LIEF::exception]'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:73:20: note:                 'LIEF::read_out_of_bound::read_out_of_bound(const char*) [inherited from LIEF::exception]'
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/exception.hpp:71:16: note: 'class LIEF::read_out_of_bound' defined here
   71 | class LIEF_API read_out_of_bound : public exception {
      |                ^~~~~~~~~~~~~~~~~
make[5]: *** [CMakeFiles/LIB_LIEF.dir/build.make:133: CMakeFiles/LIB_LIEF.dir/src/exception.cpp.o] Error 1
In file included from /home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract/Binary.hpp:30,
                 from /home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract.hpp:19,
                 from /home/estel/utilities/nvlax/build/_deps/lief_src-src/src/Abstract/json.cpp:16:
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract/Relocation.hpp:55:16: warning: 'virtual bool LIEF::Relocation::operator<(const LIEF::Relocation&) const' was hidden [-Woverloaded-virtual=]
   55 |   virtual bool operator<(const Relocation& rhs) const;
      |                ^~~~~~~~
In file included from /home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/MachO.hpp:49,
                 from /home/estel/utilities/nvlax/build/_deps/lief_src-src/src/Abstract/json.cpp:21:
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/MachO/RelocationDyld.hpp:65:8: note:   by 'bool LIEF::MachO::RelocationDyld::operator<(const LIEF::MachO::RelocationDyld&) const'
   65 |   bool operator<(const RelocationDyld& rhs) const;
      |        ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract/Relocation.hpp:61:16: warning: 'virtual bool LIEF::Relocation::operator>(const LIEF::Relocation&) const' was hidden [-Woverloaded-virtual=]
   61 |   virtual bool operator>(const Relocation& rhs) const;
      |                ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/MachO/RelocationDyld.hpp:68:8: note:   by 'bool LIEF::MachO::RelocationDyld::operator>(const LIEF::MachO::RelocationDyld&) const'
   68 |   bool operator>(const RelocationDyld& rhs) const;
      |        ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract/Relocation.hpp:58:16: warning: 'virtual bool LIEF::Relocation::operator<=(const LIEF::Relocation&) const' was hidden [-Woverloaded-virtual=]
   58 |   virtual bool operator<=(const Relocation& rhs) const;
      |                ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/MachO/RelocationDyld.hpp:69:8: note:   by 'bool LIEF::MachO::RelocationDyld::operator<=(const LIEF::MachO::RelocationDyld&) const'
   69 |   bool operator<=(const RelocationDyld& rhs) const;
      |        ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/Abstract/Relocation.hpp:64:16: warning: 'virtual bool LIEF::Relocation::operator>=(const LIEF::Relocation&) const' was hidden [-Woverloaded-virtual=]
   64 |   virtual bool operator>=(const Relocation& rhs) const;
      |                ^~~~~~~~
/home/estel/utilities/nvlax/build/_deps/lief_src-src/include/LIEF/MachO/RelocationDyld.hpp:66:8: note:   by 'bool LIEF::MachO::RelocationDyld::operator>=(const LIEF::MachO::RelocationDyld&) const'
   66 |   bool operator>=(const RelocationDyld& rhs) const;
      |        ^~~~~~~~
make[4]: *** [CMakeFiles/Makefile2:273: CMakeFiles/LIB_LIEF.dir/all] Error 2
make[3]: *** [Makefile:156: all] Error 2
make[2]: *** [CMakeFiles/LIEF.dir/build.make:86: LIEF/src/LIEF-stamp/LIEF-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/LIEF.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by SjoerdV** [comment]
@Cat-Lady with the [patch](https://github.com/illnyang/nvlax/issues/11#issuecomment-1034079793) applied you need to build with version 12 of GCC compiler (you need to have those installed as well)
`CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12 cmake ..` followed by `make`

Reference: https://aur.archlinux.org/packages/nvlax-git?O=10#comment-918104

Except it [won't help with the 555 driver](https://github.com/illnyang/nvlax/issues/24)...

**Comment by 32bitx64bit** [comment]
Forgot about this issue
