### ISSUE TITLE
Patch appears successful but has no affect (Windows / 496.49)

### ISSUE THREAD

**Issue by ninbura** [illnyang/nvlax#6]
Looks like I spoke too soon, if I run more than 3 encodes via FFmpeg I get the `[h264_nvenc @ 0000022742a41300] OpenEncodeSessionEx failed: out of memory (10): (no details)` error.

Re-installed the driver restarted and patched again, still not working. This is the output when running the patch:
```
root@ASexyCapturer:~/nvlax/build# ./nvlax_encode -i /mnt/c/Windows/System32/nvEncodeAPI64.dll -o /mnt/c/Windows/System32/nvEncodeAPI64.dll
Unable to find the section associated with CERTIFICATE_TABLE
[+] nvEncodeAPI64.dll
[+] patched successfully
root@ASexyCapturer:~/nvlax/build# ./nvlax_encode -i /mnt/c/Windows/SysWOW64/nvEncodeAPI.dll -o /mnt/c/Windows/SysWOW64/nvEncodeAPI.dll
Unable to find the section associated with CERTIFICATE_TABLE
[+] nvEncodeAPI.dll
[+] patched successfully
```

Maybe something to do with patching in place? 

PS: driver version is 496.49.

_Originally posted by @Ninbura in https://github.com/illnyang/nvlax/issues/5#issuecomment-955179993_

Thought I'd open a new issue as the issue explained in this message was not related to the original issue.

**Comment by Kidsnd274** [comment]
Same issue here with driver version 472.12

**Comment by paulgrove** [comment]
Another +1 running 496.49: (RTX 3070)
Patching:
```
./nvlax_encode -i /mnt/c/Windows/System32/nvEncodeAPI64.dll -o /mnt/c/Windows/System32/nvEncodeAPI64.dll
[+] nvEncodeAPI64.dll
[+] patched successfully
./nvlax_encode -i /mnt/c/Windows/SysWOW64/nvEncodeAPI.dll -o /mnt/c/Windows/SysWOW64/nvEncodeAPI.dll
Unable to find the section associated with CERTIFICATE_TABLE
[+] nvEncodeAPI.dll
[+] patched successfully
```
and then with ffmpeg:
```
[hevc_nvenc @ 00000266c1870bc0] OpenEncodeSessionEx failed: out of memory (10)
[hevc_nvenc @ 00000266c1870bc0] No NVENC capable devices found
```

**Comment by Shawak** [comment]
Same problem here on the 496.49 driver version, running on Windows 10

**Comment by WoodburyMan** [comment]
Same problem with 496.76 on Windows 11 and also tested on Windows 10.

**Comment by HaruSoul** [comment]
Also having the same issue. Was able to patch successfully but am still limited to 3 transcodes.
